version: '2'
services: 
  zeppelin:
    build: .
    image: tsagadai/zeppelin
    container_name: zeppelin
    environment:
      ZEPPELIN_PORT: 8090
      ZEPPELIN_JAVA_OPTS: >-
        -Dspark.driver.memory=5g
        -Dspark.executor.memory=20g
      MASTER: "spark://master:7077"
    ports:
      - 8090:8090
    volumes:
      - ./data/:/zeppelin/data
      - ./notebooks/:/zeppelin/notebook
      - ./logs:/zeppelin/logs

networks:
  default:
      external: 
        name: sparkcluster_default
